server:
  port: 8081

spring:
  application:
    name: micro-greetings-service
    
eureka:
  instance:
    nonSecurePort: ${server.port}
  client:
    serviceUrl:
      defaultZone: ${eureka.server.url:http://localhost:9000/eureka/}