server:
  port: 8082
  
spring:
  application:
    name: micro-client-service
    
eureka:
  instance:
    nonSecurePort: ${server.port}
  client:
    serviceUrl:
      defaultZone: ${eureka.server.url:http://localhost:9000/eureka/}